language: java
jdk:
    - oraclejdk8
script: ./gradlew check --stacktrace
after_success:
    - ./gradlew jacocoTestReport coveralls uploadCoverageToCodacy
    - bash <(curl -s https://codecov.io/bash)
